version: '3'
services: 
    loginapplication:
        build: .
        ports: 
            - "3069:3069"
        restart: always
    cassandra:
        image: 'cassandra'
        ports:
            - "9042:9042"
            - "9160:9160"
            - "7199:7199"
        container_name: 'cassandra'